import json

DEFAULT_MACROS_SRC_FILE = "src/catalog/default/default_functions.cpp"
DEFAULT_MACROS_JSON = "src/catalog/default/default_functions.json"

startline = '''
//===----------------------------------------------------------------------===//
// This section is automatically generated by scripts/generate_default_macros.py
// Do not edit this section manually, your changes will be overwritten
//===----------------------------------------------------------------------===//
'''

endline = '''
//===----------------------------------------------------------------------===//
// End of section generated by scripts/generate_default_macros.py
//===----------------------------------------------------------------------===//
'''

with open(DEFAULT_MACROS_SRC_FILE, 'r') as f:
    doc_text = f.read()
    if startline not in doc_text or endline not in doc_text:
        print(
            f"doc generation failed, start or end line is missing in file " + DEFAULT_MACROS_SRC_FILE
        )
f_macros_json = open(DEFAULT_MACROS_JSON)
macros_json = json.load(f_macros_json)
macros_cpp = ""

for macro in macros_json:
    line = "{" + f"{macro['schema']}, {macro['name']}, {macro['parameters']}, {macro['named_parameters']}, {macro['macro']}" + "}"
    macros_cpp += f"{',' if macros_cpp else ''}\n{line}"
    # work in progress:
    # todo: prepend comment, if any; update file: DEFAULT_MACROS_SRC_FILE
    # reference: https://github.com/c-herrewijn/duckdb-web/blob/generate_sql_function_docs/scripts/generate_sql_function_docs.py
print(macros_cpp)
print("done")
