//===----------------------------------------------------------------------===//
//                         DuckDB
//
// duckdb/functions_internal/scalar/string_functions.hpp
//
//
//===----------------------------------------------------------------------===//
// This file is automatically generated by scripts/generate_functions.py
// Do not edit this file manually, your changes will be overwritten
//===----------------------------------------------------------------------===//

#pragma once

#include "duckdb/function/function_set.hpp"

namespace duckdb {

struct Upper2Fun {
	static constexpr const char *Name = "upper2";
	static constexpr const char *Parameters = "string";
	static constexpr const char *Description = "Convert string to upper case.";
	static constexpr const char *Example = "upper('Hello')";

	static ScalarFunction GetFunction();
};

struct Ucase2Fun {
	using ALIAS = Upper2Fun;

	static constexpr const char *Name = "ucase2";
};

struct Lower2Fun {
	static constexpr const char *Name = "lower2";
	static constexpr const char *Parameters = "string";
	static constexpr const char *Description = "Convert string to lower case";
	static constexpr const char *Example = "lower('Hello')";

	static ScalarFunction GetFunction();
};

struct Lcase2Fun {
	using ALIAS = Lower2Fun;

	static constexpr const char *Name = "lcase2";
};

} // namespace duckdb
