name: InvokeCI
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      override_git_describe:
        type: string
      git_ref:
        type: string
      skip_tests:
        type: string
      run_all:
        type: string
      twine_upload:
        type: string

concurrency:
  group: invokeci-${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}-${{ inputs.override_git_describe }}-${{ inputs.git_ref }}-${{ inputs.skip_tests }}
  cancel-in-progress: true

jobs:
  extensions:
    uses: ./.github/workflows/Extensions.yml
    secrets: inherit
    with:
      override_git_describe: ${{ inputs.override_git_describe }}
      git_ref: ${{ inputs.git_ref }}
      skip_tests: ${{ inputs.skip_tests }}
      run_all: ${{ inputs.run_all }}
